package com.asg.shipping.collectionhandover.dto;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/**
 * Request DTO for creating a new Collection Handover
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class CollectionHandoverCreateDTO {

    @NotNull(message = "Transaction date is required")
    private LocalDate transactionDate;

    @NotNull(message = "Company POID is required")
    private Long companyPoid;

    // DOC_REF is intentionally absent — generated by DB trigger (RTN_GLOBAL_SEQ_NO) on INSERT.

    @Size(max = 20, message = "Location code must not exceed 20 characters")
    private String locationCode;

    private BigDecimal cashAmount;

    private BigDecimal chequeAmount;

    private BigDecimal outstandingAmount;

    private BigDecimal totalAmount;

    private Integer noofChqs;

    @Size(max = 500, message = "Location remarks must not exceed 500 characters")
    private String locRemarks;

    @Pattern(regexp = "^[YN]?$", message = "Verified received must be Y or N")
    private String verifiedRcvd;

    @Size(max = 500, message = "Main office remarks must not exceed 500 characters")
    private String mainOfcRemarks;

    @Valid
    private List<CollectionHandoverDetailCreateDTO> details;
}

