# --- DATASOURCE CONFIG ---
spring.datasource.url=jdbc:oracle:thin:@//10.100.200.85:1521/ORAVADF
spring.datasource.username=PRODUCTION
spring.datasource.password=PRODUCTION_19C#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA DIALECT ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# --- DEFAULT SCHEMA ---
spring.jpa.properties.hibernate.default_schema=PRODUCTION

spring.jpa.properties.hibernate.cache.use_second_level_cache=false
