package com.asg.shipping.collectionhandover.entity;

import com.asg.common.lib.annotation.AuditIgnore;
import com.asg.common.lib.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * Entity for AR_SH_DAY_END_CLOSE_HDR.
 *
 * TRANSACTION_POID  — generated by DB trigger via AR_SH_DAY_END_CLOSE_HDR_SEQ.
 * DOC_REF           — generated by DB trigger via RTN_GLOBAL_SEQ_NO; never set by JPA on insert.
 * LOCATION_CODE     — DB default 'PORT'.
 * VERIFIED_RCVD     — DB default 'N'.
 * Audit columns     — LASTMODIFIED_BY / LASTMODIFIED_DATE (no underscore after LAST).
 */
@Entity(name = "CollectionHandoverHdr")
@Table(name = "AR_SH_DAY_END_CLOSE_HDR")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ArShDayEndCloseHdr extends BaseEntity {

    /**
     * PK — assigned by DB trigger (AR_SH_DAY_END_CLOSE_HDR_SEQ).
     * SequenceGenerator points to the same Oracle sequence the trigger uses.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "arShDayEndCloseHdrSeq")
    @SequenceGenerator(name = "arShDayEndCloseHdrSeq",
                       sequenceName = "AR_SH_DAY_END_CLOSE_HDR_SEQ",
                       allocationSize = 1)
    @Column(name = "TRANSACTION_POID", nullable = false)
    private Long transactionPoid;

    @Column(name = "TRANSACTION_DATE")
    private LocalDate transactionDate;

    @AuditIgnore
    @Column(name = "GROUP_POID")
    private Long groupPoid;

    @AuditIgnore
    @Column(name = "COMPANY_POID")
    private Long companyPoid;

    /**
     * Generated by DB trigger (RTN_GLOBAL_SEQ_NO) on INSERT — insertable=false so JPA
     * never writes this column; it is read back after flush.
     */
    @Column(name = "DOC_REF", length = 30, insertable = false, updatable = true)
    private String docRef;

    /** DB default 'PORT' */
    @AuditIgnore
    @Column(name = "LOCATION_CODE", length = 20)
    @Builder.Default
    private String locationCode = "PORT";

    @Column(name = "CASH_AMOUNT")
    private BigDecimal cashAmount;

    @Column(name = "CHEQUE_AMOUNT")
    private BigDecimal chequeAmount;

    @AuditIgnore
    @Column(name = "OUTSTANDING_AMOUNT")
    private BigDecimal outstandingAmount;

    @Column(name = "TOTAL_AMOUNT")
    private BigDecimal totalAmount;

    @Column(name = "NOOF_CHQS")
    private Integer noofChqs;

    @Column(name = "LOC_REMARKS", length = 500)
    private String locRemarks;

    /** DB default 'N' */
    @Column(name = "VERIFIED_RCVD", length = 1)
    @Builder.Default
    private String verifiedRcvd = "N";

    @Column(name = "MAIN_OFC_REMARKS", length = 500)
    private String mainOfcRemarks;

    @AuditIgnore
    @Column(name = "DELETED", length = 1)
    private String deleted;

    @PrePersist
    protected void onCreate() {
        if (deleted == null)      deleted = "N";
        if (verifiedRcvd == null) verifiedRcvd = "N";
        if (locationCode == null) locationCode = "PORT";
    }
}

