package com.asg.shipping.containerinventorymovementupdate.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Response for Load Container Details operation.
 * Returns transactionPoid and status from PROC_SH_CNT_INSPECT_XL_UPLOAD.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class InspectionLoadResponse {
    /**
     * Transaction POID generated by the procedure (from SH_CONTAINER_INSPECT_DTL_TBL)
     */
    private String transactionPoid;

    /**
     * Status message from PROC_SH_CNT_INSPECT_XL_UPLOAD
     * Examples: "Success : Details Loaded.", "WARNING : No details in the table. Please import file."
     */
    private String status;

    /**
     * Whether the operation was successful
     */
    private Boolean success;
}

